global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'kitsu-api'
    static_configs:
      - targets: ['api:8000']
    metrics_path: /metrics

  - job_name: 'kitsu-worker'
    static_configs:
      - targets: ['worker:8000']
    metrics_path: /metrics

  - job_name: 'flower'
    static_configs:
      - targets: ['flower:5555']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
